#!/usr/bin/env bash
export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

#down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
  /tmp/leftwm-theme-down
  rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down

#boot picom or compton if it exists
if [ -x "$(command -v picom)" ]; then
  picom &> /dev/null &
elif [ -x "$(command -v compton)" ]; then
  compton &> /dev/null &
fi

#boot pasystray if it exists
if [ -x "$(command -v pasystray)" ]; then
  paysystray &> /dev/null &
fi

#boot blueman applet if it exists
if [ -x "$(command -v blueman-applet)" ]; then
  blueman-applet &> /dev/null &
fi

#set the theme.toml config
echo "LoadTheme $SCRIPTPATH/theme.toml" > $XDG_RUNTIME_DIR/leftwm/commands.pipe

#set background
if [ -x "$(command -v feh)" ]; then
  feh --bg-scale $SCRIPTPATH/background.jpg
fi

monitor="DP-2"   width=1920 offsetx=0 polybar -c $SCRIPTPATH/polybar.config "mainbar0" &> /dev/null &
monitor="DP-3"   width=1920 offsetx=0 polybar -c $SCRIPTPATH/polybar.config "mainbar0" &> /dev/null &
monitor="HDMI-0" width=3840 offsetx=0 polybar -c $SCRIPTPATH/polybar.config "mainbar0" &> /dev/null &
monitor="DP-0"   width=1920 offsetx=0 polybar -c $SCRIPTPATH/polybar.config "mainbar0" &> /dev/null &
